### PR TITLE
Upgrade to 3.1.2

### LINKED ISSUE #31: Flint 3.1 is out
### Comment:

Flint 3.1 is out.  There were presumably a couple of issues fixed in the initial 3.1 release as they're now at 3.1.2.

### PR DESCRIPTION
**Pull request by saraedum**
fixes #31

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@isuruf it seems we have no GMP build on Windows. FLINT does not support MPIR anymore.

**Comment by saraedum** [comment]
@isuruf at least the test code uses `aligned_alloc` which is not available on macOS 10.9. Is it OK to require 10.15?

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by oscarbenjamin** [comment]
> at least the test code uses `aligned_alloc` which is not available on macOS 10.9. Is it OK to require 10.15?

This can be handled with a preprocessor define:
https://github.com/flintlib/flint/blob/da447e6404373299fe6a8312053a8ab86d870229/CMake/cmake_config.h.in#L26-L31

**Comment by oscarbenjamin** [comment]
The problem with `alligned_alloc` is to do with using the CMake build script rather than the autotools one. The autotools build already handles this:
https://github.com/flintlib/flint/blob/da447e6404373299fe6a8312053a8ab86d870229/configure.ac#L1161

Note that Conda is possibly the main consumer of Flint's CMake build script which has itself been sort of deprecated by the Flint project for use on non-Windows systems: https://github.com/flintlib/flint/pull/1699. We should probably expect that either someone looking to fix the conda package will go and fix/maintain the CMake script or conda should just stop using it.

For python-flint's wheels for PyPI we just use MinGW to build everything on Windows which means that we use the autotools build always and likewise for GMP and MPFR.

Note also that as of Flint 3.1 the autotools build will generate non-portable binaries by default so some flags need to be passed to `./configure`: https://github.com/flintlib/flint/pull/1628#issuecomment-2247925325. This is generally moving in the same direction as GMP and using similar build configuration.

I think that the conda GMP package is now built with MinGW as one of Flint's dependencies but potentially the same reasons for using MinGW there would apply to Flint now or in future. Until now conda used MPIR and so could build everything with MSVC on Windows.

**Comment by saraedum** [comment]
> The problem with alligned_alloc is to do with using the CMake build script rather than the autotools one. 

The macOS build uses `./configure` though.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by oscarbenjamin** [comment]
> The macOS build uses `./configure` though.

Oh okay. I don't know enough to be able to interpret the conda-forge build scripts. I was just going by the error that you mentioned.

I think if Flint fails to build on macos because of aligned_alloc (when using the autotools build) then that would be considered a bug by the flint developers.

**Comment by saraedum** [comment]
I see. I haven't really investigated what `aligned_alloc` is about and I don't know much about macOS.

The macOS build definitely runs the `recipe/build.sh` here to build on macOS which is just configure/make/make install with some flags.

**Comment by saraedum** [comment]
If you want to create an issue on flint, I am happy to fill in more details to the extent that I understand what's going on.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@isuruf, obviously, I have no idea how Windows works. I tried to build things with `autotools_clang_conda`. Is that still supposed to work? I got this weird error here:
```
D:\bld\libflint_1722803069326\_build_env\Library\lib\clang\18\include\mmintrin.h:73:40: error: passing '__v2si' (aka 'int') to parameter of incompatible type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values)
   73 |     return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
      |                                        ^~~~~~~~~~~
```

Do I have to do the full dance that you did over at GMP to build an autoconfiscated package on Windows these days?

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@isuruf, since I couldn't figure out how to make the autotools_clang_conda build work with GMP, I disabled Windows for the moment so that the SageMath 10.4 release can go ahead.

**Comment by oscarbenjamin** [comment]
Looks like the Windows build for libflint was fixed by @isuruf in https://github.com/conda-forge/libflint-feedstock/pull/35.

Can we get the Windows package working here as well?

**Comment by oscarbenjamin** [comment]
Sorry I posted that in the wrong PR...

**Pull request merged**
